# Generated by Django 4.1.7 on 2023-06-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobie',
            new_name='mobile',
        ),
    ]
