# Generated by Django 4.1.7 on 2023-06-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_mobie_patient_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
